# Generated by Django 5.2.1 on 2026-08-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('booking', 'Booking Related'), ('ev_charging', 'EV Charging'), ('complaint', 'Complaint'), ('feedback', 'Feedback'), ('partnership', 'Partnership'), ('other', 'Other')], default='general', max_length=20, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('is_replied', models.BooleanField(default=False, verbose_name='replied')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ServiGo', max_length=100, verbose_name='site name')),
                ('site_tagline', models.CharField(default='Your trusted home services partner', max_length=200, verbose_name='site tagline')),
                ('contact_email', models.EmailField(default='support@servigo.com', max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=20, verbose_name='contact phone')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='maintenance mode')),
                ('maintenance_message', models.TextField(blank=True, verbose_name='maintenance message')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
