# Generated by Django 5.2.1 on 2026-08-10 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class', max_length=50, verbose_name='icon class')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='category image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'service category',
                'verbose_name_plural': 'service categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('short_description', models.TextField(max_length=500, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in minutes', verbose_name='estimated duration (minutes)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='service image')),
                ('what_included', models.TextField(blank=True, help_text='One item per line', verbose_name="what's included")),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['category__display_order', 'display_order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
