# Generated by Django 5.2.1 on 2026-08-10 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EVChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='station name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('pincode', models.CharField(max_length=10, verbose_name='pincode')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('google_maps_url', models.URLField(blank=True, verbose_name='Google Maps URL')),
                ('charger_type', models.CharField(choices=[('type1', 'Type 1 (SAE J1772)'), ('type2', 'Type 2 (Mennekes)'), ('ccs1', 'CCS1 (Combo 1)'), ('ccs2', 'CCS2 (Combo 2)'), ('chademo', 'CHAdeMO'), ('tesla', 'Tesla Supercharger'), ('gb_t', 'GB/T')], default='ccs2', max_length=20, verbose_name='charger type')),
                ('charging_speed_kw', models.PositiveIntegerField(help_text='Maximum charging speed in kW', verbose_name='charging speed (kW)')),
                ('price_per_kwh', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price per kWh')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('offline', 'Offline')], default='available', max_length=20, verbose_name='status')),
                ('total_ports', models.PositiveIntegerField(default=1, verbose_name='total ports')),
                ('available_ports', models.PositiveIntegerField(default=1, verbose_name='available ports')),
                ('opens_at', models.TimeField(help_text='24-hour format', verbose_name='opens at')),
                ('closes_at', models.TimeField(help_text='24-hour format', verbose_name='closes at')),
                ('is_24_hours', models.BooleanField(default=False, verbose_name='24 hours')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ev_stations/', verbose_name='station image')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'EV charging station',
                'verbose_name_plural': 'EV charging stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EVChargingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='customer name')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='customer phone')),
                ('booking_date', models.DateField(verbose_name='booking date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('estimated_kwh', models.DecimalField(decimal_places=2, help_text='Estimated energy consumption', max_digits=6, verbose_name='estimated kWh')),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='estimated cost')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Charging Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_bookings', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ev_charging.evchargingstation', verbose_name='station')),
            ],
            options={
                'verbose_name': 'EV charging booking',
                'verbose_name_plural': 'EV charging bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
